services:
  proxy:
    image: localhost-proxy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    secrets:
      - ssh_host_key
      - ssh_password
    dns:
      - 8.8.8.8
      - 8.8.4.4

secrets:
  ssh_host_key:
    file: ./ssh_host_key
  ssh_password:
    file: ./ssh_password
